In [9]:
import pandas as pd
import numpy as np
from timeit import default_timer

In [11]:
# df = pd.read_csv('test.csv')
# user_id_col = 'user_id'
# item_id_col = 'item_id'
df = pd.read_csv('../songs_recommender/preprocessed_data/user_songs.csv')
df = df[df['listen_count'] > 50]
user_id_col = 'user_id'
item_id_col = 'song'
len(df)

4782

In [12]:
all_users = list(df[user_id_col].unique())
all_items = list(df[item_id_col].unique())
print(all_users)
print(all_items)

['d13609d62db6df876d3cc388225478618bb7b912', '50996bbabb6f7857bf0c8019435b5246a0e45cfd', '5ea608df0357ec4fda191cb9316fe8e6e65e3777', 'bb85bb79612e5373ac714fcd4469cabeb5ed94e1', 'c012ec364329bb08cbe3e62fe76db31f8c5d8ec3', '70caceccaa745b6f7bc2898a154538eb1ada4d5a', '972cce803aa7beceaa7d0039e4c7c0ff097e4d55', 'd2232ac7a1ec17b283b5dff243161902b2cb706c', 'f5363481018dc87e8b06f9451e99804610a594fa', 'f1bdbb9fb7399b402a09fa124210dedf78e76034', '2be4e2736f580dd4fe7b489f675935ccfad0a453', '7d3cb0aca2aff23e5fd06e34d66ec16ccfdaab4e', 'ac41abca59d8cab8ec94e0f912a313a32e9736a9', 'd4438263e80ea31cbcca30005873a4074a0c248e', '66ff466e107e9bcd7c6f2c59501ed0d7844c26c0', '6040ed6d4e10f09e6cccd64c819c684531abe682', 'e9d8dfd545ca342caa23202ceb2d969ce04dc030', '38767872c514c1b43bab5c7b213b6702980d87c0', 'dc20d1116f083d39d3035e13e266b45d72f9a627', '9a22b4d8ef6cbb7376124d216f9be2d2c04693df', 'ce7169aed3eae1d598f3a465b8a0d95fe2749f05', '0ee4cadeda8f05272083df630fdc8986afd47e9e', '09318175bf2f39d316f41d80fbfc4e

In [13]:
item_users_df = df.groupby([item_id_col]).agg({user_id_col: (lambda x: list(x.unique()))})
item_users_df = item_users_df.rename(columns={user_id_col: 'users'}).reset_index()
item_users_df

song  \
0                              #40 - DAVE MATTHEWS BAND   
1                         'Round Midnight - Miles Davis   
2                'Til We Die (Album Version) - Slipknot   
3                 'Till I Collapse - Eminem / Nate Dogg   
4           (Antichrist Television Blues) - Arcade Fire   
5     (I've Had) The Time Of My Life - Bill Medley &...   
6                              (Nice Dream) - Radiohead   
7           (They Long To Be) Close To You - Carpenters   
8     (You Drive Me) Crazy (The Stop Remix!) - Britn...   
9                                   (iii) - The Gerbils   
10               ...Baby One More Time - Britney Spears   
11                         ..Come Around - Collie Buddz   
12                              16 Candles - The Crests   
13                                   19-2000 - Gorillaz   
14                               1991 - Crystal Castles   
15    21 Guns [feat. Green Day & The Cast Of America...   
16                                      22 - Lily Allen   
17                                221 - keller williams   
18                                             24 - Jem   
19          240 Years Before Your Time - The Black Keys   
20                                   3 - Britney Spears   
21    369 (feat. B.o.B.) [Step Up 2 The Streets O.S....   
22                   3AM (LP Version) - matchbox twenty   
23                                  5.45 - Gang Of Four   
24                                 505 - Arctic Monkeys   
25                                      83 - John Mayer   
26    A Beggar On A Beach Of Gold - Mike And The Mec...   
27                                A Cura - Lulu  Santos   
28                                A Day Late - Anberlin   
29                   A Days Work (feat. P.O.S) - BK-One   
...                                                 ...   
2179                You Give Love A Bad Name - Bon Jovi   
2180                             You Gotta Be - Des'ree   
2181                               You Hid - Toro Y Moi   
2182               You Know I'm No Good - Amy Winehouse   
2183           You Know What You Are? - Nine Inch Nails   
2184      You Learn (Album Version) - Alanis Morissette   
2185                   You Only Live Once - The Strokes   
2186                      You Sang To Me - Marc Anthony   
2187  You Think I Ain't Worth A Dollar_ But I Feel L...   
2188    You'd Be So Nice To Come Home To - Julie London   
2189  You'll Never Know (My Love) (Bovellian 07 Mix)...   
2190                   You're A Wolf (Album) - Sea Wolf   
2191                You're Ever So Inviting - Underoath   
2192                     You're The One - Dwight Yoakam   
2193       You've Got The Love - Florence + The Machine   
2194                           Young - Hollywood Undead   
2195  Young Folks - Peter_ Bjorn and John Featuring ...   
2196   Your Guardian Angel - The Red Jumpsuit Apparatus   
2197          Your Hand In Mine - Explosions In The Sky   
2198       Your Place In The World - The Space Brothers   
2199             Your Rocky Spine - Great Lake Swimmers   
2200                            Your Woman - White Town   
2201                        Yours Alone - Dum Dum Girls   
2202                Youth Against Fascism - Sonic Youth   
2203  Youth Of The Nation (2006 Remastered Album Ver...   
2204                               Yön hetket - Yölintu   
2205                             Zero - Yeah Yeah Yeahs   
2206             paranoid android - Christopher O'Riley   
2207                               re:stacks - Bon Iver   
2208                              Época - Gotan Project   

                                                  users  
0     [43dba0787e3a1f12d28077e7cfd0b9db328cfc71, 1f4...  
1            [219fa7aa1c423cfb994f1f1f2109e68d75758e1d]  
2     [632a7c62c94ff08252fd1cde7de732be9f384212, aaa...  
3     [0ed5f1391a9b5d1962a8fb9149c1969ca02bd495, 7e9...  
4            [2e4cdf4a4b0e26a1577f218440830ac83ce07122]  
5            [60791213a2ca4c631bf779da4c6d96

In [14]:
user_items_df = df.groupby([user_id_col]).agg({item_id_col: (lambda x: list(x.unique()))})
user_items_df = user_items_df.rename(columns={item_id_col: 'items'}).reset_index()
user_items_df

user_id  \
0     002543003041db1d049206b09426d5cdffc0f451   
1     0031572620fa7f18487d3ea22935eb28410ecc4c   
2     004c7be9336ca88824e1e0b09ef9a2168200fa33   
3     00669ce738f766eb289c85751406e138818d40f7   
4     00787bdcd936a4dd76062a9b71da2694e4859707   
5     0091e0326c4c034cc04be6454742912845740a1f   
6     009855b9d2c4857379df94e351af3b0e1a05d531   
7     00a443baf550f4bbdd974ba73720abf2759166f3   
8     00bbb48c752fc88b5c89f48dd589470b655e1a3d   
9     00bc896afc13f29692958ec5a0a26891962db7ce   
10    00bd0afdfd0d2a3551ab50c079844a6d0a315434   
11    00ed445effd95cfcfc288c5be4288ec8e8bc78cd   
12    00f95c5243e490b54a5a9d84816306d591edcea5   
13    0118e22e6baa2a0342ce77061d735d1e6aee5b89   
14    0144fafaa7cd0347fa585eb69f7063c051b64fbb   
15    014a2063c4ba673902b6483bead96a7e07c4e65a   
16    01725f9a4beb50e63bf43031bb66d13146950fff   
17    017db04a4c7362734eb16838980b3a1a3bdb2754   
18    0181c36f49953188d993fcb87d690edc58b97f56   
19    018c020deb5a40983fb7f6c59d95b47f1d1680bb   
20    019203f26b0adde655119bfc43a1e59ee8eeb582   
21    01b8f48413e061ed3f6764a6eaef30b97cfcf68b   
22    01d0e117a44702e6ea3b5d66e322ed9c37fcfbfb   
23    024ca7ed3ccce1a88df54b403540ca0ed9be6fa4   
24    028f39ee932e9d870793b4a59abda4f1fd68de41   
25    029928de35c2e5473a3ad89082ddca001387c27a   
26    029ccfe48497d04d4d43c9f9f325da4d50f13241   
27    02b91bce6ace3b1d8ee56cbae424b9337264cff1   
28    02bcb9c3860e8c731b5b3f199586721157a4a304   
29    02cb15390967a57896d3561f3a53bbfb31fdb063   
...                                        ...   
3098  fdbe1a45bf70c71727e81405ecf42555959eb453   
3099  fdc8b2fb77b90905fa7c596e13c0085d7be67042   
3100  fdd19586391d44c9148c1bb761f0d01cd1c228ca   
3101  fe104858f929d5e59426946be4b5732c139048de   
3102  fe1595ad5f3919851f2bcf59138359533ff22d65   
3103  fe2314259d533156c740a8a62930957414a79ef8   
3104  fe2d77de7e57f3b3eedcf473545110b13ca03426   
3105  fe3a1bdcb3032302629b2962f65b4bce4218d319   
3106  fe3a66e7ac3234087e4a231b80c260930d96ba51   
3107  fe4102ebf4631ecac5254f73f66313c101b20919   
3108  fe7138fb077191162a691b80860c0341550a469c   
3109  fea8be855e756e4dda274c96be7b93ff901dea14   
3110  fed93dbe1b9f6db94a2afaf6a8a502b0b66633cf   
3111  fef074d3c34166dfe2d9691edd36d7b048523436   
3112  ff00562a44aba604a786c4d46b6c48e642aab97f   
3113  ff19c1e49bbfb81dd9de29bc21961740c7bbb9b2   
3114  ff3b46927f0d0cafdf5fe39b498766909d0c5dfd   
3115  ff4129221bd95775a872a8ae36acc6cbe24bd5f3   
3116  ff439fbb23ab079d18458a69806ada35a14d2b45   
3117  ff49c9c042a6fdfa2f68e36d91a4241d2c51db90   
3118  ff5073ccb8a3c63e02de29c182841f08fbef106f   
3119  ff5bd85d9b195a3303796c20da660bb65f230bb9   
3120  ff706464229ac76d1ee71dbceb1b59b7718a1df2   
3121  ff7bd64071ad1c542a23551e8680975455e85b88   
3122  ff94b8f73cc7d4a9fa32d7b8fa9fc31fef7347cc   
3123  ffae55912ef3e44b81d9d62f6e97d619927e9e4e   
3124  ffbbfe2317f07bfab035d08c3ef1e70555f8341b   
3125  ffc41c16fc584c914cef99375d37d4fac9388b08   
3126  ffdba77092d34f570244582029b18ef5cab70aca   
3127  fff03efd1550136063389fa71125194614e1c68f   

                                                  items  
0                   [Heads Will Roll - Yeah Yeah Yeahs]  
1     [Last Cup Of Sorrow - Faith No More, Influenci...  
2                               [A Cura - Lulu  Santos]  
3     [You're The One - Dwight Yoakam, Resurrection ...  
4                   [Radio Nowhere - Bruce Springsteen]  
5     [Monster Mash - Bobby "Boris" Pickett, Hey Gir...  
6                     [Almeno Tu Nell'Universo - Elisa]  
7                        [Buttons - The Pussycat Dolls]  
8     [I Second That Emotion - Smokey Robinson & The...  
9                    [Campus (Album) - Vampire Weekend]  
10    [Hero Of War - Rise Against, Helicopter - Bloc...  
11                         [Riot Of Violence - Kreator]  
12              [Do U Wanna Ride - Jay-Z / John Legend]  
13                       [Oh Jungleland - Simple Minds]  
14    [Chambermaid Swing - Parov Stelar, So Easy - R...  
15    [Mah

In [15]:
def get_users(item_id):
    """Get unique users for a given item"""
    item_data = item_users_df[item_users_df[item_id_col] == item_id]
    item_users = (item_data['users'].values)[0]
    return item_users

def construct_cooccurence_matrix(items):
    """Construct cooccurence matrix"""
    # Initialize the item cooccurence matrix
    len_items = len(items)
    cooccurence_matrix = np.matrix(np.zeros(shape=(len_items, len_items)), float)

    # Calculate similarity between item pairs for upper triangular elements
    for i, item_i in enumerate(items):
        # Get unique users of item_i
        users_i = set(get_users(item_i))

        for j, item_j in enumerate(items):
            if i == j:
                cooccurence_matrix[i, j] = 1.0
                continue
            if i > j:
                continue #same result as corresponding j, i

            # Get unique users of item_j
            users_j = set(get_users(item_j))

            # Calculate intersection of users of items i and j
            users_intersection = users_i.intersection(users_j)
            no_of_common_users = len(users_intersection)
            # Calculate cooccurence_matrix[i,j] as Jaccard Index
            if no_of_common_users != 0:
                # Calculate union of users of items i and j
                users_union = users_i.union(users_j)
                no_of_all_users = len(users_union)
                if no_of_all_users != 0:
                    cooccurence_matrix[i, j] = float(
                        no_of_common_users) / float(no_of_all_users)
                    cooccurence_matrix[j, i] = cooccurence_matrix[i, j]
    return cooccurence_matrix

In [16]:
start_time = default_timer()
cooccurence_matrix = construct_cooccurence_matrix(all_items)
end_time = default_timer()
print("Time Taken : {} sec".format(end_time-start_time))
#cooccurence_matrix

Time Taken : 1720.767814158 sec


In [18]:
#https://stackoverflow.com/questions/31518937/convert-two-column-data-frame-to-occurrence-matrix-in-pandas
#pd.get_dummies(df.item_id)
uim_df = pd.get_dummies(df[item_id_col]).groupby(df[user_id_col]).apply(max)
uim_df.head()

#40 - DAVE MATTHEWS BAND  \
user_id                                                              
002543003041db1d049206b09426d5cdffc0f451                       0.0   
0031572620fa7f18487d3ea22935eb28410ecc4c                       0.0   
004c7be9336ca88824e1e0b09ef9a2168200fa33                       0.0   
00669ce738f766eb289c85751406e138818d40f7                       0.0   
00787bdcd936a4dd76062a9b71da2694e4859707                       0.0   

                                          'Round Midnight - Miles Davis  \
user_id                                                                   
002543003041db1d049206b09426d5cdffc0f451                            0.0   
0031572620fa7f18487d3ea22935eb28410ecc4c                            0.0   
004c7be9336ca88824e1e0b09ef9a2168200fa33                            0.0   
00669ce738f766eb289c85751406e138818d40f7                            0.0   
00787bdcd936a4dd76062a9b71da2694e4859707                            0.0   

                                          'Til We Die (Album Version) - Slipknot  \
user_id                                                                            
002543003041db1d049206b09426d5cdffc0f451                                     0.0   
0031572620fa7f18487d3ea22935eb28410ecc4c                                     0.0   
004c7be9336ca88824e1e0b09ef9a2168200fa33                                     0.0   
00669ce738f766eb289c85751406e138818d40f7                                     0.0   
00787bdcd936a4dd76062a9b71da2694e4859707                                     0.0   

                                          'Till I Collapse - Eminem / Nate Dogg  \
user_id                                                                           
002543003041db1d049206b09426d5cdffc0f451                                    0.0   
0031572620fa7f18487d3ea22935eb28410ecc4c                                    0.0   
004c7be9336ca88824e1e0b09ef9a2168200fa33                                    0.0   
00669ce738f766eb289c85751406e138818d40f7                                    0.0   
00787bdcd936a4dd76062a9b71da2694e4859707                                    0.0   

                                          (Antichrist Television Blues) - Arcade Fire  \
user_id                                                                                 
002543003041db1d049206b09426d5cdffc0f451                                          0.0   
0031572620fa7f18487d3ea22935eb28410ecc4c                                          0.0   
004c7be9336ca88824e1e0b09ef9a2168200fa33                                          0.0   
00669ce738f766eb289c85751406e138818d40f7                                          0.0   
00787bdcd936a4dd76062a9b71da2694e4859707                                          0.0   

                                          (I've Had) The Time Of My Life - Bill Medley & Jennifer Warnes  \
user_id                                                                                                    
002543003041db1d049206b09426d5cdffc0f451                                                0.0                
0031572620fa7f18487d3ea22935eb28410ecc4c                                                0.0                
004c7be9336ca88824e1e0b09ef9a2168200fa33                                                0.0                
00669ce738f766eb289c85751406e138818d40f7                                                0.0                
00787bdcd936a4dd76062a9b71da2694e4859707                                                0.0                

                                          (Nice Dream) - Radiohead  \
user_id                                                              
002543003041db1d049206b09426d5cdffc0f451                       0.0   
0031572620fa7f18487d3ea22935eb28410ecc4c                       0.0   
004c7be9336ca88824e1e0b09ef9a2168200fa33                       0.0   
00669ce738f766eb289c85751406e138818d40f7                       0.0   
00787bdcd936a4dd76062a9b71da2694e4859707             

In [48]:
df[df[item_id_col] == 'If It Means A Lot To You - A Day To Remember']

Unnamed: 0                                   user_id  \
541      1255102  0ed5f1391a9b5d1962a8fb9149c1969ca02bd495   
2365      943235  9fcc2313dcc742342bda6377e040ab0cfba7dc37   

                                              song  listen_count  
541   If It Means A Lot To You - A Day To Remember           121  
2365  If It Means A Lot To You - A Day To Remember            67

In [49]:
df[df[user_id_col] == '0ed5f1391a9b5d1962a8fb9149c1969ca02bd495']

Unnamed: 0                                   user_id  \
334      1255081  0ed5f1391a9b5d1962a8fb9149c1969ca02bd495   
541      1255102  0ed5f1391a9b5d1962a8fb9149c1969ca02bd495   
2786     1255104  0ed5f1391a9b5d1962a8fb9149c1969ca02bd495   
2844     1255077  0ed5f1391a9b5d1962a8fb9149c1969ca02bd495   

                                              song  listen_count  
334           Have Faith In Me - A Day To Remember           147  
541   If It Means A Lot To You - A Day To Remember           121  
2786    The Downfall Of Us All - A Day To Remember            63  
2844         'Till I Collapse - Eminem / Nate Dogg            62

In [50]:
df[df[user_id_col] == '9fcc2313dcc742342bda6377e040ab0cfba7dc37']

Unnamed: 0                                   user_id  \
2365      943235  9fcc2313dcc742342bda6377e040ab0cfba7dc37   
3618      943233  9fcc2313dcc742342bda6377e040ab0cfba7dc37   

                                              song  listen_count  
2365  If It Means A Lot To You - A Day To Remember            67  
3618          Are You Dead Yet - Children Of Bodom            57

In [20]:
uim = uim_df.as_matrix()
uim

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [25]:
non_zero_count = np.count_nonzero(uim)
count = uim.size
density = non_zero_count/count
print(non_zero_count, count, density)

4782 6909752 0.0006920653592198388


In [26]:
uim.T

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [27]:
item_item_intersection = np.dot(uim.T, uim)
item_item_intersection

array([[ 3.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  3., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  3.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [43]:
item_item_intersection_df = pd.DataFrame(item_item_intersection, columns=uim_df.columns, index=uim_df.columns)
item_item_intersection_df.to_csv('item_item_intersection.csv')

In [95]:
item1 = "'Round Midnight - Miles Davis"
item2 = "16 Candles - The Crests"
# item1 = "(Antichrist Television Blues) - Arcade Fire"
# item2 = "..Come Around - Collie Buddz"
users_item1 = set(df[df[item_id_col] == item1][user_id_col].values)
users_item2 = set(df[df[item_id_col] == item2][user_id_col].values)
print(users_item1)
print(users_item2)
common_users = users_item1.intersection(users_item2)
union_users = users_item1.union(users_item2)
print(common_users)
print(union_users)
print(len(common_users), len(union_users))

{'219fa7aa1c423cfb994f1f1f2109e68d75758e1d'}
{'810bfc92d58786310e798c1229c701ecae84716e', 'a7189c4e2b56c1b2ce6dd72ec5c364f20cf1911d', '484fca36d83b8a8e1a2ba5a1097a2d9058c6a7bc', 'eb671bc38ee5d5d13b815fef98f1e9de44580c45', 'e3b2f4c2b4746079162f760288d29c7718d6ff7a', '57be950acbe5a926eee7ea17c111a168865b98c4', 'c64d4b93776e101c97574a70ca2fbf3f3b242734', '81bce979b2c1c0c98694034dcfc0b5c270b92f9a', 'a583f14dbe09d30fb45983fa53c03941a66d1626', 'b32572321802200f21de39b10be217f8381ccce7', '3528490a2da13fea741d972e17debb2be6a3dc48', '13ac51ac39c657a0034e7253499bee84fe6d75ed'}
set()
{'810bfc92d58786310e798c1229c701ecae84716e', 'a7189c4e2b56c1b2ce6dd72ec5c364f20cf1911d', '484fca36d83b8a8e1a2ba5a1097a2d9058c6a7bc', 'eb671bc38ee5d5d13b815fef98f1e9de44580c45', 'e3b2f4c2b4746079162f760288d29c7718d6ff7a', '57be950acbe5a926eee7ea17c111a168865b98c4', '219fa7aa1c423cfb994f1f1f2109e68d75758e1d', 'c64d4b93776e101c97574a70ca2fbf3f3b242734', '81bce979b2c1c0c98694034dcfc0b5c270b92f9a', 'a583f14dbe09d30fb45983

In [28]:
flip_uim = 1-uim
flip_uim

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [29]:
flip_uim.T

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [30]:
users_left_out_of_union = np.dot(flip_uim.T, flip_uim)
users_left_out_of_union

array([[ 3125.,  3124.,  3122., ...,  3122.,  3124.,  3124.],
       [ 3124.,  3127.,  3124., ...,  3124.,  3126.,  3126.],
       [ 3122.,  3124.,  3125., ...,  3122.,  3124.,  3124.],
       ..., 
       [ 3122.,  3124.,  3122., ...,  3125.,  3124.,  3124.],
       [ 3124.,  3126.,  3124., ...,  3124.,  3127.,  3126.],
       [ 3124.,  3126.,  3124., ...,  3124.,  3126.,  3127.]])

In [31]:
items = list(uim_df.columns)
no_of_items = len(items)
users = list(uim_df.index)
no_of_users = len(users)
print("No of Items : ", no_of_items)
print("No of Users : ", no_of_users)

No of Items :  2209
No of Users :  3128


In [32]:
item_item_union = no_of_users - users_left_out_of_union
item_item_union

array([[ 3.,  4.,  6., ...,  6.,  4.,  4.],
       [ 4.,  1.,  4., ...,  4.,  2.,  2.],
       [ 6.,  4.,  3., ...,  6.,  4.,  4.],
       ..., 
       [ 6.,  4.,  6., ...,  3.,  4.,  4.],
       [ 4.,  2.,  4., ...,  4.,  1.,  2.],
       [ 4.,  2.,  4., ...,  4.,  2.,  1.]])

In [52]:
item_item_union_df = pd.DataFrame(item_item_union, columns=uim_df.columns, index=uim_df.columns)
item_item_union_df.to_csv('item_item_union.csv')

In [33]:
item_item_jaccard = item_item_intersection/item_item_union
item_item_jaccard

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [66]:
item_item_jaccard_df = pd.DataFrame(item_item_jaccard, columns=uim_df.columns, index=uim_df.columns)
item_item_jaccard_df.to_csv('item_item_jaccard.csv')

In [89]:
cooccurence_matrix

matrix([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  1.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [90]:
item_item_jaccard

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [67]:
cooccurence_matrix_df = pd.DataFrame(cooccurence_matrix, columns=uim_df.columns, index=uim_df.columns)
cooccurence_matrix_df.to_csv('cooccurence_matrix.csv')

In [70]:
item_item_jaccard_df.head()

#40 - DAVE MATTHEWS BAND  \
#40 - DAVE MATTHEWS BAND                                          1.0   
'Round Midnight - Miles Davis                                     0.0   
'Til We Die (Album Version) - Slipknot                            0.0   
'Till I Collapse - Eminem / Nate Dogg                             0.0   
(Antichrist Television Blues) - Arcade Fire                       0.0   

                                             'Round Midnight - Miles Davis  \
#40 - DAVE MATTHEWS BAND                                               0.0   
'Round Midnight - Miles Davis                                          1.0   
'Til We Die (Album Version) - Slipknot                                 0.0   
'Till I Collapse - Eminem / Nate Dogg                                  0.0   
(Antichrist Television Blues) - Arcade Fire                            0.0   

                                             'Til We Die (Album Version) - Slipknot  \
#40 - DAVE MATTHEWS BAND                                                        0.0   
'Round Midnight - Miles Davis                                                   0.0   
'Til We Die (Album Version) - Slipknot                                          1.0   
'Till I Collapse - Eminem / Nate Dogg                                           0.0   
(Antichrist Television Blues) - Arcade Fire                                     0.0   

                                             'Till I Collapse - Eminem / Nate Dogg  \
#40 - DAVE MATTHEWS BAND                                                       0.0   
'Round Midnight - Miles Davis                                                  0.0   
'Til We Die (Album Version) - Slipknot                                         0.0   
'Till I Collapse - Eminem / Nate Dogg                                          1.0   
(Antichrist Television Blues) - Arcade Fire                                    0.0   

                                             (Antichrist Television Blues) - Arcade Fire  \
#40 - DAVE MATTHEWS BAND                                                             0.0   
'Round Midnight - Miles Davis                                                        0.0   
'Til We Die (Album Version) - Slipknot                                               0.0   
'Till I Collapse - Eminem / Nate Dogg                                                0.0   
(Antichrist Television Blues) - Arcade Fire                                          1.0   

                                             (I've Had) The Time Of My Life - Bill Medley & Jennifer Warnes  \
#40 - DAVE MATTHEWS BAND                                                                   0.0                
'Round Midnight - Miles Davis                                                              0.0                
'Til We Die (Album Version) - Slipknot                                                     0.0                
'Till I Collapse - Eminem / Nate Dogg                                                      0.0                
(Antichrist Television Blues) - Arcade Fire                                                0.0                

                                             (Nice Dream) - Radiohead  \
#40 - DAVE MATTHEWS BAND                                          0.0   
'Round Midnight - Miles Davis                                     0.0   
'Til We Die (Album Version) - Slipknot                            0.0   
'Till I Collapse - Eminem / Nate Dogg                             0.0   
(Antichrist Television Blues) - Arcade Fire                       0.0   

                                             (They Long To Be) Close To You - Carpenters  \
#40 - DAVE MATTHEWS BAND                                                             0.0   
'Round Midnight - Miles Davis                                                        0.0   
'Til We Die (Album Version) - Slipknot                                               0.0   
'Till I Collapse - Eminem / Nate Dogg                                 

In [69]:
cooccurence_matrix_df.head()

#40 - DAVE MATTHEWS BAND  \
#40 - DAVE MATTHEWS BAND                                          1.0   
'Round Midnight - Miles Davis                                     0.0   
'Til We Die (Album Version) - Slipknot                            0.0   
'Till I Collapse - Eminem / Nate Dogg                             0.0   
(Antichrist Television Blues) - Arcade Fire                       0.0   

                                             'Round Midnight - Miles Davis  \
#40 - DAVE MATTHEWS BAND                                               0.0   
'Round Midnight - Miles Davis                                          1.0   
'Til We Die (Album Version) - Slipknot                                 0.0   
'Till I Collapse - Eminem / Nate Dogg                                  0.0   
(Antichrist Television Blues) - Arcade Fire                            0.0   

                                             'Til We Die (Album Version) - Slipknot  \
#40 - DAVE MATTHEWS BAND                                                        0.0   
'Round Midnight - Miles Davis                                                   0.0   
'Til We Die (Album Version) - Slipknot                                          1.0   
'Till I Collapse - Eminem / Nate Dogg                                           0.0   
(Antichrist Television Blues) - Arcade Fire                                     0.0   

                                             'Till I Collapse - Eminem / Nate Dogg  \
#40 - DAVE MATTHEWS BAND                                                       0.0   
'Round Midnight - Miles Davis                                                  0.0   
'Til We Die (Album Version) - Slipknot                                         0.0   
'Till I Collapse - Eminem / Nate Dogg                                          1.0   
(Antichrist Television Blues) - Arcade Fire                                    0.0   

                                             (Antichrist Television Blues) - Arcade Fire  \
#40 - DAVE MATTHEWS BAND                                                             0.0   
'Round Midnight - Miles Davis                                                        0.0   
'Til We Die (Album Version) - Slipknot                                               0.0   
'Till I Collapse - Eminem / Nate Dogg                                                0.0   
(Antichrist Television Blues) - Arcade Fire                                          1.0   

                                             (I've Had) The Time Of My Life - Bill Medley & Jennifer Warnes  \
#40 - DAVE MATTHEWS BAND                                                                   0.0                
'Round Midnight - Miles Davis                                                              0.0                
'Til We Die (Album Version) - Slipknot                                                     0.0                
'Till I Collapse - Eminem / Nate Dogg                                                      0.0                
(Antichrist Television Blues) - Arcade Fire                                                0.0                

                                             (Nice Dream) - Radiohead  \
#40 - DAVE MATTHEWS BAND                                          0.0   
'Round Midnight - Miles Davis                                     0.0   
'Til We Die (Album Version) - Slipknot                            0.0   
'Till I Collapse - Eminem / Nate Dogg                             0.0   
(Antichrist Television Blues) - Arcade Fire                       0.0   

                                             (They Long To Be) Close To You - Carpenters  \
#40 - DAVE MATTHEWS BAND                                                             0.0   
'Round Midnight - Miles Davis                                                        0.0   
'Til We Die (Album Version) - Slipknot                                               0.0   
'Till I Collapse - Eminem / Nate Dogg                                 

In [72]:
item_item_jaccard_df.equals(cooccurence_matrix_df)
item_item_jaccard_df.index.names == cooccurence_matrix_df.index.names

True

In [51]:
#https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.equal.html
#https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.all.html#numpy.all
res = np.equal(cooccurence_matrix, item_item_jaccard)#.all()
res

matrix([[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ..., 
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]], dtype=bool)

In [73]:
res_df = pd.DataFrame(res, columns=uim_df.columns, index=uim_df.columns)
res_df.to_csv('res.csv')

matrix([[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ..., 
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]], dtype=bool)

In [74]:
res_df

#40 - DAVE MATTHEWS BAND  \
#40 - DAVE MATTHEWS BAND                                               True   
'Round Midnight - Miles Davis                                          True   
'Til We Die (Album Version) - Slipknot                                 True   
'Till I Collapse - Eminem / Nate Dogg                                  True   
(Antichrist Television Blues) - Arcade Fire                            True   
(I've Had) The Time Of My Life - Bill Medley & ...                     True   
(Nice Dream) - Radiohead                                               True   
(They Long To Be) Close To You - Carpenters                            True   
(You Drive Me) Crazy (The Stop Remix!) - Britne...                     True   
(iii) - The Gerbils                                                    True   
...Baby One More Time - Britney Spears                                 True   
..Come Around - Collie Buddz                                           True   
16 Candles - The Crests                                                True   
19-2000 - Gorillaz                                                     True   
1991 - Crystal Castles                                                 True   
21 Guns [feat. Green Day & The Cast Of American...                     True   
22 - Lily Allen                                                        True   
221 - keller williams                                                  True   
24 - Jem                                                               True   
240 Years Before Your Time - The Black Keys                            True   
3 - Britney Spears                                                     True   
369 (feat. B.o.B.) [Step Up 2 The Streets O.S.T...                     True   
3AM (LP Version) - matchbox twenty                                     True   
5.45 - Gang Of Four                                                    True   
505 - Arctic Monkeys                                                   True   
83 - John Mayer                                                        True   
A Beggar On A Beach Of Gold - Mike And The Mech...                     True   
A Cura - Lulu  Santos                                                  True   
A Day Late - Anberlin                                                  True   
A Days Work (feat. P.O.S) - BK-One                                     True   
...                                                                     ...   
You Give Love A Bad Name - Bon Jovi                                    True   
You Gotta Be - Des'ree                                                 True   
You Hid - Toro Y Moi                                                   True   
You Know I'm No Good - Amy Winehouse                                   True   
You Know What You Are? - Nine Inch Nails                               True   
You Learn (Album Version) - Alanis Morissette                          True   
You Only Live Once - The Strokes                                       True   
You Sang To Me - Marc Anthony                                          True   
You Think I Ain't Worth A Dollar_ But I Feel Li...                     True   
You'd Be So Nice To Come Home To - Julie London                        True   
You'll Never Know (My Love) (Bovellian 07 Mix) ...                     True   
You're A Wolf (Album) - Sea Wolf                                       True   
You're Ever So Inviting - Underoath                                    True   
You're The One - Dwight Yoakam                                         True   
You've Got The Love - Florence + The Machine                           True   
Young - Hollywood Undead                                               True   
Young Folks - Peter_ Bjorn and John Featuring V...                     True   
Your Guardian Angel - The Red Jumpsuit Apparatus                       True   
Your Hand In Mine - Explosions In The Sky                              True   
Your Place In The Worl

In [93]:
item1 = "(Antichrist Television Blues) - Arcade Fire"
item2 = "..Come Around - Collie Buddz"

item1 = "'Round Midnight - Miles Davis"
item2 = "16 Candles - The Crests"
users_item1 = get_users(item1)
users_item2 = get_users(item2)
print(users_item1)
print(users_item2)
print(item_item_jaccard_df[item1][item2])
print(cooccurence_matrix_df[item1][item2])
print(res_df[item1][item2])

['219fa7aa1c423cfb994f1f1f2109e68d75758e1d']
['57be950acbe5a926eee7ea17c111a168865b98c4', 'a7189c4e2b56c1b2ce6dd72ec5c364f20cf1911d', '81bce979b2c1c0c98694034dcfc0b5c270b92f9a', 'b32572321802200f21de39b10be217f8381ccce7', '3528490a2da13fea741d972e17debb2be6a3dc48', '810bfc92d58786310e798c1229c701ecae84716e', 'c64d4b93776e101c97574a70ca2fbf3f3b242734', '484fca36d83b8a8e1a2ba5a1097a2d9058c6a7bc', 'eb671bc38ee5d5d13b815fef98f1e9de44580c45', '13ac51ac39c657a0034e7253499bee84fe6d75ed', 'a583f14dbe09d30fb45983fa53c03941a66d1626', 'e3b2f4c2b4746079162f760288d29c7718d6ff7a']
0.0
0.0
True


In [87]:
sub_df = df[(df[item_id_col] == item1) | (df[item_id_col] == item2)]
sub_df

Unnamed: 0                                   user_id  \
25        225526  38767872c514c1b43bab5c7b213b6702980d87c0   
1383      534979  2e4cdf4a4b0e26a1577f218440830ac83ce07122   
1583      939527  faa6962ada2b39cd900d8fb144b2e15e2ca3f72a   
2456     1236731  d34d523fb05593e9e68e42b28fe4022f0f05eb9d   

                                             song  listen_count  
25                   ..Come Around - Collie Buddz           401  
1383  (Antichrist Television Blues) - Arcade Fire            84  
1583                 ..Come Around - Collie Buddz            79  
2456                 ..Come Around - Collie Buddz            66

In [88]:
sub_df.to_csv('sub_df.csv', index=False)

In [135]:
user_items = list(df[df[user_id_col] == '9fcc2313dcc742342bda6377e040ab0cfba7dc37'][item_id_col].unique())

In [136]:
user_items

['If It Means A Lot To You - A Day To Remember',
 'Are You Dead Yet - Children Of Bodom']

In [137]:
sub_cooccurence_matrix_df = item_item_jaccard_df.loc[user_items]
sub_cooccurence_matrix_df

#40 - DAVE MATTHEWS BAND  \
If It Means A Lot To You - A Day To Remember                       0.0   
Are You Dead Yet - Children Of Bodom                               0.0   

                                              'Round Midnight - Miles Davis  \
If It Means A Lot To You - A Day To Remember                            0.0   
Are You Dead Yet - Children Of Bodom                                    0.0   

                                              'Til We Die (Album Version) - Slipknot  \
If It Means A Lot To You - A Day To Remember                                     0.0   
Are You Dead Yet - Children Of Bodom                                             0.0   

                                              'Till I Collapse - Eminem / Nate Dogg  \
If It Means A Lot To You - A Day To Remember                               0.333333   
Are You Dead Yet - Children Of Bodom                                       0.000000   

                                              (Antichrist Television Blues) - Arcade Fire  \
If It Means A Lot To You - A Day To Remember                                          0.0   
Are You Dead Yet - Children Of Bodom                                                  0.0   

                                              (I've Had) The Time Of My Life - Bill Medley & Jennifer Warnes  \
If It Means A Lot To You - A Day To Remember                                                0.0                
Are You Dead Yet - Children Of Bodom                                                        0.0                

                                              (Nice Dream) - Radiohead  \
If It Means A Lot To You - A Day To Remember                       0.0   
Are You Dead Yet - Children Of Bodom                               0.0   

                                              (They Long To Be) Close To You - Carpenters  \
If It Means A Lot To You - A Day To Remember                                          0.0   
Are You Dead Yet - Children Of Bodom                                                  0.0   

                                              (You Drive Me) Crazy (The Stop Remix!) - Britney Spears  \
If It Means A Lot To You - A Day To Remember                                                0.0         
Are You Dead Yet - Children Of Bodom                                                        0.0         

                                              (iii) - The Gerbils  \
If It Means A Lot To You - A Day To Remember                  0.0   
Are You Dead Yet - Children Of Bodom                          0.0   

                                                      ...            \
If It Means A Lot To You - A Day To Remember          ...             
Are You Dead Yet - Children Of Bodom                  ...             

                                              Your Rocky Spine - Great Lake Swimmers  \
If It Means A Lot To You - A Day To Remember                                     0.0   
Are You Dead Yet - Children Of Bodom                                             0.0   

                                              Your Woman - White Town  \
If It Means A Lot To You - A Day To Remember                      0.0   
Are You Dead Yet - Children Of Bodom                              0.0   

                                              Yours Alone - Dum Dum Girls  \
If It Means A Lot To You - A Day To Remember                          0.0   
Are You Dead Yet - Children Of Bodom                                  0.0   

                                              Youth Against Fascism - Sonic Youth  \
If It Means A Lot To You - A Day To Remember                                  0.0   
Are You Dead Yet - Children Of Bodom                                          0.0   

                                              Youth Of The Nation (2006 Remastered Album Version) - P.O.D.  \
If It Means A Lot To You - A Day To Remember                                                0.0              
Are You

In [138]:
item_scores = sub_cooccurence_matrix_df.sum(axis=0) / float(sub_cooccurence_matrix_df.shape[0])
item_scores.sort_values(inplace=True, ascending=False)
item_scores = item_scores[item_scores>0]

In [139]:
print(user_items)

['If It Means A Lot To You - A Day To Remember', 'Are You Dead Yet - Children Of Bodom']


In [146]:
user_id = '9fcc2313dcc742342bda6377e040ab0cfba7dc37'
columns = ['user_id', 'item_id', 'score', 'rank']
no_of_recs = 2
rank = 1
items = []
for item_id, score in item_scores.items():
    if item_id in user_items:
        continue
    if rank > no_of_recs:
        break
    item_dict = {
        'user_id' : user_id,
        'item_id' : item_id,
        'score' : score,
        'rank' : rank
    }
    print(user_id, item_id, score, rank)
    items.append(item_dict)
    rank += 1
res1df = pd.DataFrame(items, columns=columns)
res1df

9fcc2313dcc742342bda6377e040ab0cfba7dc37 Have Faith In Me - A Day To Remember 0.25 1
9fcc2313dcc742342bda6377e040ab0cfba7dc37 The Downfall Of Us All - A Day To Remember 0.166666666667 2


user_id  \
0  9fcc2313dcc742342bda6377e040ab0cfba7dc37   
1  9fcc2313dcc742342bda6377e040ab0cfba7dc37   

                                      item_id     score  rank  
0        Have Faith In Me - A Day To Remember  0.250000     1  
1  The Downfall Of Us All - A Day To Remember  0.166667     2

In [120]:
user_sim_scores

#40 - DAVE MATTHEWS BAND                                                                 0.000000
Rebirthing (Album Version) - Skillet                                                     0.000000
Rebirth of Slick (Cool Like Dat) (2005 Digital Remaster) (Explicit) - Digable Planets    0.000000
Rebel Yell - Billy Idol                                                                  0.000000
Reason I'm Alive (Explicit) - Drowning Pool                                              0.000000
Real Girl - Mutya Buena                                                                  0.000000
Ready_ Steady_ Go (Album Version) - Paul Oakenfold                                       0.000000
Ready to Flow 2008 - Mike Nero                                                           0.000000
Read My Mind - The Killers                                                               0.000000
Reach Out - Refused                                                                      0.000000
Re: Your Brains - Jo