In [41]:
from sklearn.model_selection import KFold
from sklearn.model_selection import LeavePOut
import numpy as np

In [57]:
learners = np.array([1,2,3,4,5,6,7,8,9,10, 11,12,13,14,15,16,17,18,19,20])
kf = KFold(n_splits=10)
i = 0
experiments = dict()
experiments['train'] = dict()
experiments['test'] = dict()
for train_indices, test_indices in kf.split(learners):
    #print("%s %s" % (train_indices, test_indices))
    train = set(learners[train_indices])
    test = set(learners[test_indices])
    #print(train, test)
    experiments['train'][i] = train
    experiments['test'][i] = test
    i += 1

In [64]:
all_learners = set(learners)

all_test_learners = set()
for i in experiments['test']:
    all_test_learners |= set(experiments['test'][i])
print(all_learners - all_test_learners)

all_train_learners = set()
for i in experiments['train']:
    all_train_learners |= set(experiments['train'][i])    
print(all_learners - all_train_learners)

set()
set()


In [45]:
lpo = LeavePOut(p=2)
n = 0
for train_indices, test_indices in lpo.split(X):
    #print("%s %s" % (train_indices, test_indices))
    train = X[train_indices]
    test = X[test_indices]
    print(train, test)
    n += 1
print(n)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [1 2]
[ 2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [1 3]
[ 2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [1 4]
[ 2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [1 5]
[ 2  3  4  5  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [1 6]
[ 2  3  4  5  6  8  9 10 11 12 13 14 15 16 17 18 19 20] [1 7]
[ 2  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18 19 20] [1 8]
[ 2  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18 19 20] [1 9]
[ 2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19 20] [ 1 10]
[ 2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18 19 20] [ 1 11]
[ 2  3  4  5  6  7  8  9 10 11 13 14 15 16 17 18 19 20] [ 1 12]
[ 2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18 19 20] [ 1 13]
[ 2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18 19 20] [ 1 14]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 16 17 18 19 20] [ 1 15]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 17 18 19 20] [ 1 16]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 18 19 20] 

In [27]:
import os
import pandas as pd
data_dir = '../books_recommender/preprocessed_metadata'
data = os.path.join(data_dir, 'learner_books_info_close_min_10_events.csv')
events_df = pd.read_csv(data)

In [47]:
valid_ages_df = events_df[(events_df['age'] >= 5.0) & (events_df['age'] <= 20.0)]
learners = np.array(valid_ages_df['learner_id'].unique())
no_of_learners = len(learners)
no_of_test_learners = int(no_of_learners * 0.2)
no_of_train_learners = no_of_learners - no_of_test_learners

In [48]:
print(no_of_learners, no_of_train_learners, no_of_test_learners)

1148 919 229


In [65]:
kf = KFold(n_splits=10)
i = 0
experiments = dict()
experiments['train'] = dict()
experiments['test'] = dict()
for train_indices, test_indices in kf.split(learners):
    #print("%s %s" % (train_indices, test_indices))
    train = set(learners[train_indices])
    test = set(learners[test_indices])
    #print(train, test)
    experiments['train'][i] = train
    experiments['test'][i] = test
    i += 1

In [67]:
all_learners = set(learners)

all_test_learners = set()
for i in experiments['test']:
    all_test_learners |= set(experiments['test'][i])
print(all_learners - all_test_learners)

all_train_learners = set()
for i in experiments['train']:
    all_train_learners |= set(experiments['train'][i])    
print(all_learners - all_train_learners)

set()
set()
